# Site
title:              Andrea Grisafi
bio:                'Fullstack .NET Developer - Milano'
description:        "Sviluppatore fullstack .NET - Milano."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder2.jpg'
tiled_bg:           false 
locale:             it_IT
url:                https://andreagrisafi.it


# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   andreagrisafi

# Social
twitter:            sgri_dev
github-url:         sgridev
linkedin:          andreagrisafi
#youtube-channel:    UCA5UQ85gBvVdQY2-LSWAOyA

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# jekyll-mentions:
#     base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
